#!/bin/sh

HEADER=$(sed -n '1p' "$1")
NEWLINE=$(sed -n '2p' "$1")
HEADER_REGEXP="^(feat|fix|docs|refactor)"`
             `"(\([a-z0-9_]{1,20}\))?: "`
             `"[a-z].{0,78}[^\.[:space:]]$"

echo "$HEADER"  | grep -qE "$HEADER_REGEXP" || exit 1
echo "$NEWLINE" | grep -qE "^$"             || exit 1

